- name: Ideacy
  content:
    This forum is dedicated to posts about the project itself.
- name: About
  parent: Ideacy
  content: >
    This website allows members to post content in a tree structure. Furthermore each post has an expiry date set by the users contribution of likes.
    Each user accrues time as long as he is a member. This accrued time is used in likes on posts.
    When a post expires it will no longer be visible on the site.
    This website is an instance of Idea merit project at
    https://gitlab.com/jakub.c/idea-merit-frontend
    https://gitlab.com/jakub.c/idea-merit-backend
- name: Rules
  parent: Ideacy
  content:
    Do not post anything that is illegal.
- name: Coding
  content:
    This is a forum dedicated to any coding/software development/programming ideas.
- name: Food
  content:
    This is a forum dedicated to food. Share recipes, hints and anything related to food.
- name: Misc
  content:
    This is a forum dedicated ideas not fit to any previous forum.