# postgresql+psycopg2://user:password@host/database
database: postgresql+psycopg2://postgres:abc@localhost/IdeaMerit
other:
  secret_key: development-secret
  jwt_secret_key: development-secret
  bcrypt_rounds: 8
limit:
  max_emails_per_account: 3
  email_verification_hours: 48
  password_reset_hours: 48
vouch:
  resource_speed_per_vouch: "4: 0.2, 5: 0.4, 6: 0.6, 7: 0.8, 8: 1"
