# postgresql+psycopg2://user:password@host/database
database: postgresql+psycopg2://postgres:abc@localhost/IdeaMeritTest
other:
  secret_key: test-secret
  jwt_secret_key: test-secret
  bcrypt_rounds: 4
