# postgresql+psycopg2://user:password@host/database
database: postgresql+psycopg2://postgres:abc@localhost/IdeaMeritTest
other:
  secret_key: test-secret
  jwt_secret_key: test-secret
  bcrypt_rounds: 4
vouch:
  resource_speed_per_vouch: "1: 0.5, 2: 1"